# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '13_11_ListarEpisodios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'Alamofire'
	pod 'Kingfisher'

  # Pods for 13_11_ListarEpisodios

  target '13_11_ListarEpisodiosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '13_11_ListarEpisodiosUITests' do
    # Pods for testing
  end

end
