# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'imagedownload' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Kingfisher', '~> 5.0'

  # Pods for imagedownload

  target 'imagedownloadTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'imagedownloadUITests' do
    # Pods for testing
  end

end
