# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '11_11_conversordemoedas' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'Alamofire'
  # Pods for 11_11_conversordemoedas

  target '11_11_conversordemoedasTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '11_11_conversordemoedasUITests' do
    # Pods for testing
  end

end
